name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: hackathon-cp-project-team-1

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/1054015443281/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account:  my-github-actions-sa@hackathon-cp-project-team-1.iam.gserviceaccount.com

    - name: Set repository for authentication
      run: |
        gcloud iam service-accounts add-iam-policy-binding \
        my-github-actions-sa@hackathon-cp-project-team-1.iam.gserviceaccount.com \
        --role="roles/iam.workloadIdentityUser" \
        --member="principalSet://iam.googleapis.com/projects/1054015443281/locations/global/workloadIdentityPools/github-actions-pool/attribute.repository/backstage-dummy-org/Rag-Demo-SDP"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply --auto-approve
      run: terraform apply -auto-approve
      env:
        GOOGLE_CLOUD_PROJECT: hackathon-cp-project-team-1